/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/. 
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.1.8-160
 *
 */
import { FluenceClient, PeerIdB58 } from '@fluencelabs/fluence';
import { RequestFlowBuilder } from '@fluencelabs/fluence/dist/api.unstable';
import { RequestFlow } from '@fluencelabs/fluence/dist/internal/RequestFlow';



export async function greeter(client: FluenceClient, payloads: {greet:boolean;name:string;node:string;service_id:string}[], config?: {ttl?: number}): Promise<string[]> {
    let request: RequestFlow;
    const promise = new Promise<string[]>((resolve, reject) => {
        request = new RequestFlowBuilder()
            .disableInjections()
            .withTTL(config?.ttl || 5000)
            .withRawScript(
                `
(xor
 (seq
  (seq
   (seq
    (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
    (call %init_peer_id% ("getDataSrv" "payloads") [] payloads)
   )
   (fold payloads p
    (par
     (seq
      (seq
       (call -relay- ("op" "noop") [])
       (xor
        (seq
         (call -relay- ("op" "noop") [])
         (call p.$.node! (p.$.service_id! "greeting") [p.$.name! p.$.greet!] $results)
        )
        (seq
         (call -relay- ("op" "noop") [])
         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
        )
       )
      )
      (call %init_peer_id% ("op" "noop") [])
     )
     (next p)
    )
   )
  )
  (xor
   (call %init_peer_id% ("callbackSrv" "response") [$results])
   (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
  )
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
)

            `,
            )
            .configHandler((h) => {
                h.on('getDataSrv', '-relay-', () => {
                    return client.relayPeerId!;
                });
                h.on('getDataSrv', 'payloads', () => {return payloads;});
                h.onEvent('callbackSrv', 'response', (args) => {
  const [res] = args;
  resolve(res);
});

                h.onEvent('errorHandlingSrv', 'error', (args) => {
                    // assuming error is the single argument
                    const [err] = args;
                    reject(err);
                });
            })
            .handleScriptError(reject)
            .handleTimeout(() => {
                reject('Request timed out for greeter');
            })
            .build();
    });
    await client.initiateFlow(request!);
    return promise;
}
      